print("--- Shuffled Deck ------------------------")
var deck = Deck(shuffleDeck: true)
print(deck)
print("--- Normal Deck ------------------------")
deck = Deck(shuffleDeck: false)
print(deck.fullDescription)
print("-- Draw first card --")
var card1 = deck.draw()
print("Drawn card: \(card1)")
print(deck.fullDescription)